telstrapurple/DevEvents

- readme.md
A little thing to help navigate the README
> make it easy to jump down to the contributing section

- readme.md
Let's show what is important first, people will eventually get to FAQ at the end.
> move FAQ to the end

- readme.md
Updated some dates, some changes required on our website, and fixed the date order of the design conference.
> Some corrections to Web Directions events

- readme.md
Added Brisbane Yow from December, apparently we had 2  and AISA Security Conference for next year October
> Added Yow Brisbane 2017 and AISA Cyber Conference

- readme.md
Adding CrikeyCon 5 which happens in February next year.
> Add CrikeyCon 5

- readme.md
Ruxcon normally has an interesting mix of Dev, Ops and Security folks attending.
> Added Ruxcon 2017

- contributing.md
We updated the contribution instructions in https://github.com/Readify/DevEvents/pull/12 but the changes got lost after we merged https://github.com/Readify/DevEvents/pull/10
> Update contribution instructions

- readme.md
From Agile Australia website, the event is in Melbourne.
http://agileaustralia.com.au/2018/venue/
> This event is in VIC, not NSW.

- readme.md
> Added AWS Summit to the list

- readme.md
Added I Love APIs conference for 27/02/2018
> Add I Love APIs conference

- readme.md
Clean up some naughty whitespace that has crept in from Excel copy/paste
> Whitespace cleanup

- readme.md
The website says it's in June, not March!
> Corrected Angular Conf Dates

- readme.md
Was held in Adelaide (and other states) in 2017. Probably will be again in 2018
> Add Global DevOps Bootcamp

- readme.md
https://twitter.com/martinabbott/status/943039798092148736
> Add Global Integration Bootcamp

- readme.md
Added upcoming courses by https://twitter.com/queenslandfplab
> feature: λ

- readme.md
Added Agile Aus workshops and changed Agile Aus to Agile Aus conference
> Add Agile Aus workshops

- readme.md
Added Web Directions Design Leaders event
> Add additional Web Directions event

- readme.md
- Added CFP start/close dates to table
- Added honourable mentions, all-year CFP and TBD lists
- Changed date format to DD-MMM-YYYY
- Crossed out past events
- Added Perth Web Accessibility Camp, Decompress, CampJS
Closes #39 cc @amykapernick @fendersperth
Need to figure out whether to keep the DD/MM/YYYY format (i.e. change back) or change to DD-MMM-YYYY and change CONTRIBUTING.md and the 2017 table...
> Adding changes from https://github.com/Readify/DevEvents/pull/39

- readme.md
https://2018.container.camp/au/
> Added Container Camp in May

- readme.md
Additionally:
- Fixed Container Camp link
- Crossed out closed CPF dates
> Added YOW! West

- readme.md
See https://github.com/Readify/DevEvents/pull/43#issuecomment-365873117
> Update Web Directions AI date

- readme.md
- Levels should now be in the main section
- PWAC has already happened and is in the main section
Sorry, I missed these last night
> Added YOW! Conferences and moved a couple of things around

- readme.md
> Removing a US conference

- readme.md
:wave: 
* CSSConf
* JSConf
* Decompress
* DevOps Talks
* MongoDB.Local
Can be merged tonight (to be 100% accurate) 😸
> Strike out past conferences in VIC and NSW

- readme.md
~~Global Integration Bootcamp~~
> Global Integration Bootcamp is over

- readme.md
It's actually in July
https://www.levelsconf.com/
> Levels Conf fix

- readme.md
Crosses out Cyber Security, AWS Summit, Web Direction Design/Design Leaders.
Corrects name of Voxxed Days.
Confirms and adds details of DDD [Melb|Syd].
> Some updates

- readme.md
@leftclickben mentioned Latency conf today and I was going to look it up but couldn't see it here...
Fixed.
> Add Latency Conf 2018

- readme.md
> Added API days

- readme.md
This kicks off a new 2019 section. Hopefully I put it in the right place. Bring on 2019!
> Adds RubyConf AU 2019

- readme.md
Added various conferences for 2019
> Added conferences for 2019

- readme.md
> Add 2019 events and remove some old stuff

- readme.md
It would be contraversial to hold it in Sydney...
> Correct YOW! Melbourne URL

- readme.md
The website says it's in Melbourne.
> Update TConf 2019 location to VIC

- readme.md
> Add Perth Azure bootcamp

- 2016.md
- 2017.md
The 2017 and 2016 date formatting was different to 2018 & 2019, meaning that the parsing was a pain.
This PR makes it consistent.
> Adding consistency to the date formatting

- readme.md
Sydney version of Global DevOps bootcamp in one month
> Added Global DevOps bootcamp

- readme.md
> Added XConf dates

- readme.md
> Add DevOpsDays Sydney

- readme.md
> Added Summit for Microsoft Business Applications

- readme.md
If you have some questions, please let me know - roman.prokashev@jetbrains.com. Thank you!
> Added JetBrains events in Australia

- readme.md
I removed all year specific URLs
> Adding 2020 events

- readme.md
Updated Latency Conf dates as it runs for two days
> Update Latency URL and dates

- readme.md
Didn't check thorougly enough while reviewing #132
Couldn't find the CFP open/close dates, so I assume they're not published yet?
> Update dates for NDC Sydney 2020

- readme.md
Added Serverless Days Melbourne; NDC Melbourne and Sydney CFP links.
> Add CFPs for various conferences

- readme.md
Added Serverless days Sydney and ComponentConf CFP links
> Added CFP links

- readme.md
> Added API days Melb

- readme.md
> Update DataEngConf and Pycon

- readme.md
Added details for upcoming Web Directions events in person and our CFPs
> Added Web Directions 2022 in person events and CFPs

- Meetups/VIC.md
MelbJS has moved http://melbjs.com/
> Update MelbJS location to CultureAmp

- readme.md
Sorted by date ascending
Added additional events (DevFest, LAST)
Moved past events to Completed section
> Additional events; sorted by date
